### PR TITLE
Added migration guide

### PR DESCRIPTION
**Pull request by astrofrog**
@ebressert - does this look ok? Is there anything else you can think of that we need to mention here?

### CODE REVIEW

**Comment by ebressert** [comment]
What are the plans for Tablesets and the ability to connect to SQL DB clients?

**Comment by astrofrog** [comment]
Ah yes, I need to mention table sets too. No plans right now to integrate into Astropy though as far as I can see. One option I was considering is to keep `atpy` as a legacy package, then create `atpy2` (or something better named) which basically uses what's in Astropy and just adds SQL and table set functionality. What do you think?

**Comment by ebressert** [comment]
That sounds like the best option. Let's go forward with that.

**Comment by astrofrog** [comment]
Ok - and just to be clear, this will be a separate repository, but we'll keep this one as-is for backward-compatibility (whereas the new one will adopt the new Astropy Table interface). I'll merge in this migration guide and we can add to it over time.

**Pull request merged**
